// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLSAxt5eiJBFhbtThddPa9R0G0kEQwco',
    appId: '1:361921636266:web:f1fb58cf138656f48aadd3',
    messagingSenderId: '361921636266',
    projectId: 'mosellapp2',
    authDomain: 'mosellapp2.firebaseapp.com',
    storageBucket: 'mosellapp2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirPeOJS-2GPlKfSoEJU8AZ1CUr_Z2K1c',
    appId: '1:361921636266:android:8fcbc50c4f147a458aadd3',
    messagingSenderId: '361921636266',
    projectId: 'mosellapp2',
    storageBucket: 'mosellapp2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBOBNXU8Xy3uME2igF5gUerOk1Wsw-coI',
    appId: '1:361921636266:ios:c877de2cc79d22768aadd3',
    messagingSenderId: '361921636266',
    projectId: 'mosellapp2',
    storageBucket: 'mosellapp2.firebasestorage.app',
    iosBundleId: 'com.example.mosell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBOBNXU8Xy3uME2igF5gUerOk1Wsw-coI',
    appId: '1:361921636266:ios:c877de2cc79d22768aadd3',
    messagingSenderId: '361921636266',
    projectId: 'mosellapp2',
    storageBucket: 'mosellapp2.firebasestorage.app',
    iosBundleId: 'com.example.mosell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPLSAxt5eiJBFhbtThddPa9R0G0kEQwco',
    appId: '1:361921636266:web:c9fab4a032cf58358aadd3',
    messagingSenderId: '361921636266',
    projectId: 'mosellapp2',
    authDomain: 'mosellapp2.firebaseapp.com',
    storageBucket: 'mosellapp2.firebasestorage.app',
  );
}
